#ifndef SANS_TITRE_GLOBAL_HH
#define SANS_TITRE_GLOBAL_HH

#include <QtCore/qglobal.h>

#if defined(SANS_TITRE_LIBRARY)
#  define SANS_TITRESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SANS_TITRESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SANS_TITRE_GLOBAL_HH
